### ISSUE TITLE
Concretar la fecha de la reunión telemática y la vía de la misma.

### ISSUE THREAD

**Issue by UO284262** [Arquisoft/lomap_es2c#12]
Es necesario que cada uno de los miembros del equipo comunique su disponibilidad. En clase se había mencionado el jueves como posible día.

**Comment by uo269745** [comment]
Yo tendría disponibilidad el jueves todo el día.

**Comment by uo282154** [comment]
Yo puedo el jueves a partir de las 16:00 a cualquier hora

**Comment by Jeept09** [comment]
Yo puedo después de las 14:30

**Comment by uo276839** [comment]
Yo puedo después de las 15:30

**Comment by UO284262** [comment]
Mi disponibilidad es a partir de las 11:00

**Comment by UO284262** [comment]
Pues si os parece bien a todos lo fechamos a las 17:00?

**Comment by uo269745** [comment]
Por mí perfecto

**Comment by uo276839** [comment]
Por mí bien también

**Comment by Jeept09** [comment]
Por mí no hay problema

**Comment by uo282154** [comment]
Perfecto entonces a las 17
