### ISSUE TITLE
Bitácora de errores

### ISSUE THREAD

**Issue by UO284262** [Arquisoft/lomap_es2c#70]
Estructura de los errores -> [ STATUS ASOCIADO | MENSAJE DE ERROR | DESCRIPCIÓN ]

**Comment by UO284262** [comment]
Ejemplo: 505 | "Credenciales no coincidentes" | Se intenta iniciar sesión con un usuario que no existe

**Comment by uo282716** [comment]
506 | "Contraseña errónea" | Se intenta iniciar sesión con un usuario que existe, pero la contraseña no coincide

**Comment by uo282154** [comment]
507 | "Usuario no encontrado para listar detalles" | Se ejecuta el listar detalles de un usuario que no está en la base de datos

**Comment by uo282154** [comment]
508| "Error en la conexión con la base de datos" | Error ya sea al iniciar la conexión a la bd o al hacer la petición

**Comment by uo282716** [comment]
509| "Nombre de usuario ya existente" | Se registra un usuario con un nombre de usuario que ya está en la bd
