### ISSUE TITLE
Bitácora de puntos de acceso HTTP

### ISSUE THREAD

**Issue by UO284262** [Arquisoft/lomap_es2c#76]
Estructura de punto de acceso -> [ URL ASOCIADA |  MÉTODO HTTP | PARÁMETROS/RETURN | DESCRIPCIÓN]

**Comment by UO284262** [comment]
Ejemplo: /user/details | GET | return: User | Devuelve los detalles del usuario en sesión

**Comment by UO284262** [comment]
/usermanager/edit | POST | param: User / return: User | Recibe los datos actualizados de un usuario y lo devuelve tras actualizarlo

**Comment by UO284262** [comment]
/friendmanager/friends | POST | param: User / return: User[] | Recibe un usuario y devuelve sus amigos

**Comment by UO284262** [comment]
/friendmanager/add | POST | param: String / return: User | Recibe un username, lo comprueba en la base de datos, si existe le manda una solicitud de amistas y devuelve el usuario al que le mando la solicitud

**Comment by UO284262** [comment]
/usermanager/find/username | GET | return: User | recibe un username y devuelve el User asociado, si existe

**Comment by UO284262** [comment]
/mapmanager/addgorup | POST | param: Group, User / return: Group[] | Recibe un usuario y un grupo, añade ese grupo al POD del usuario y devuelve toda la lista de grupos del usuario actualizado

**Comment by UO284262** [comment]
/friendmanager/updaterequest/:status | POST | param: FriendRequest / return: string | Recibe una solicitud de amistad y su nuevo estado como parámetros. Cambia ese estado y devuelve un string informativo

**Comment by UO284262** [comment]
/usermanager/editpsw | param: newpsw, oldpsw / return: User | Recibe la contraseña antigua que acaba de introducir el usuario. La nueva que se quiere poner. Comprueba que la antigua coincide, actualiza a la nueva si no es la misma. Devuelve el user extraido de base de datos tras actualizar.

**Comment by uo282154** [comment]
/friendmanager/requests | post | param: User / return: FriendRequest[] | Recibe n usuario y devuelve las solicitudes de amistad que le han mandado y todavía no han sido ni aceptadas ni rechazadas (las que estan pendientes).
